-- TASK 1
SELECT WORKDEPT, SUM(SALARY) SUM_SALARY
FROM EMPLOYEE
GROUP BY WORKDEPT;

-- TASK 2
SELECT WORKDEPT, COUNT(*) AS EMP_COUNT
FROM EMPLOYEE
GROUP BY WORKDEPT;

-- TASK 3
SELECT WORKDEPT, COUNT(*) AS EMP_COUNT
FROM EMPLOYEE
GROUP BY WORKDEPT
HAVING COUNT(*) > 3;

-- TASK 4
SELECT COUNT(*) AS DESIGNER, WORKDEPT
FROM EMPLOYEE
WHERE JOB = 'DESIGNER'
GROUP BY WORKDEPT;

-- TASK 5
SELECT WORKDEPT, SEX, AVG(SALARY) AS "AVG-SALARY", AVG(COMM) AS "AVG-COMM", AVG(BONUS) AS "AVG-BONUS", COUNT(*)
FROM EMPLOYEE
GROUP BY WORKDEPT, SEX
HAVING COUNT(*) > 2;

-- TASK 6
SELECT WORKDEPT,
	DECIMAL(AVG(COMM), 9, 2) AS "AVG-COMM",
	DECIMAL(AVG(BONUS), 9, 2) AS "AVG-BONUS"
FROM EMPLOYEE
GROUP BY WORKDEPT
HAVING AVG(BONUS) > 500 AND AVG(COMM) > 2000;