-- TASK 1
SELECT EMPNO, LASTNAME, SALARY, WORKDEPT
FROM EMPLOYEE
WHERE SALARY > 22000 AND SALARY < 24000
AND WORKDEPT IN ('D11', 'D21');


-- TASK 2
SELECT EDLEVEL, MIN(SALARY) AS "MIN-SALARY", MAX(SALARY) AS "MAX-SALARY", 
DECIMAL(ROUND(AVG(SALARY), 2), 9, 2) AS "AVG-SALARY", COUNT(*) AS "COUNT-EMPLOYEE"
FROM EMPLOYEE
WHERE EDLEVEL = 16
GROUP BY EDLEVEL;

-- TASK 3
SELECT WORKDEPT, MIN(SALARY) AS "MIN-SALARY", MAX(SALARY) AS "MAX-SALARY", 
DECIMAL(ROUND(AVG(SALARY), 2), 9, 2) AS "AVG-SALARY", COUNT(*) AS "COUNT-EMPLOYEE" 
FROM EMPLOYEE
GROUP BY WORKDEPT
HAVING COUNT(*) > 5;