-- TASK 1
SELECT WORKDEPT, EMPNO, LASTNAME, SALARY
FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SAALRY) FROM  EMPLOYEE)+ 5000
ORDER BY WORKDEPT, EMPNO;


--TAKS 2
SELECT EMPNO, LASTNAME
FROM EMPLOYEE
WHERE EMPNO IN (SELECT EMPNBO FROM EMP_ACT);

-- TASK 3
SELECT PROJNO, DAYS(PRENDATE) - DAYS(PRSTDATE) AS DAYS
FROM PROJECT
WHERE DAYS(PRENDATE) - DAYS(PRSTDATE) = (SELECT MIN(DAYS(PRENDATE) - DAYS(PRSTDATE)) FROM PROJECT);

-- TASK 4
SELECT E.WORKDEPT, D.DEPTNAME, E.LASTNAME, E.FIRSTNME 
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.WORKDEPT = D.DEPTNO
AND E.WORKDEPT NOT IN (SELECT WORKDEPT FROM EMPLOYEE WHERE SEX = 'F');

-- TASK 5
SELECT LASTNAME, JOB, EDLEVEL, SALARY, YEAR(DATE('2000-01-01') - HIREDATE) AS YEARS
FROM EMPLOYEE
WHERE (JOB, EDLEVEL) IN (SELECT JOB, EDLEVEL FROM EMPLOYEE WHERE LASTNAME = 'STERN')
ORDER BY SALARY DESC;
