SELECT EMPNO, LASTNAME, BIRTHDATE, SALARY
FROM EMPLOYEE
WHERE SALARY > 30000
ORDER BY SALARY DESC
;

-- Task 02
SELECT LASTNAME, FIRSTNME, WORKDEPT
FROM EMPLOYEE
ORDER BY WORKDEPT DESC, LASTNAME DESC
;

-- TASK03
SELECT DISTINCT EDLEVEL
FROM EMPLOYEE
ORDER BY EDLEVEL DESC;


-- TASK 04


-- TASK 05
SELECT LASTNAME, SALARY, BONUS
FROM EMPLOYEE
WHERE SEX = 'M';

-- TASK 06
SELECT LASTNAME, SALARY, COMM
FROM EMPLOYEE
WHERE SALARY >= 20000 
	AND YEAR(HIREDATE) > 1979 -- HIREDATE > '1979-12-31'
;

-- TASK 07
SELECT LASTNAME, SALARY, BONUS, COMM
FROM EMPLOYEE
WHERE (SALARY > 22000
 	AND BONUS = 400)
	OR (BONUS = 500
	AND COMM < 1900)
ORDER BY LASTNAME;

-- TASK 08
SELECT LASTNAME, SALARY, BONUS, COMM
FROM EMPLOYEE
WHERE SALARY > 22000
	AND (BONUS = 400 OR BONUS = 500)
	AND COMM < 1900
ORDER BY LASTNAME;

-- TAKS 09
SELECT PROJNO, ACTNO, EMSTDATE, EMENDATE
FROM EMP_ACT
WHERE PROJNO LIKE 'AD%'
	AND ACTNO IN (10, 80, 180)
ORDER BY ACTNO
;
-- TASK 10
SELECT MGRNO, DEPTNO
FROM DEPARTMENT
WHERE MGRNO IS NOT NULL
ORDER BY MGRNO;
