-- TASK 1

SELECT LASTNAME, FIRSTNME, DEPTNAME 
FROM EMPLOYEE, DEPARTMENT
WHERE WORKDEPT = DEPTNO
ORDER BY FIRSTNME;

-- TASK 2

SELECT LASTNAME, FIRSTNME, JOB, DEPTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE WORKDEPT = DEPTNO
AND DEPTNO BETWEEN 'A02' AND 'D22'
AND JOB <> 'MANAGER'
ORDER BY DEPTNAME, JOB, LASTNAME;

-- TASK 3

SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNME, JOB
FROM  EMPLOYEE E, DEPARTMENT D
WHERE E.EMPNO = D.MGRNO
ORDER BY D.DEPTNAME;

-- TASK 4

SELECT D.DEPTNAME, E.LASTNAME, E.FIRSTNME, JOB
FROM  EMPLOYEE E, DEPARTMENT D
WHERE E.WORKDEPT = D.DEPTNO
AND JOB = 'MANAGER'
ORDER BY D.DEPTNAME;

-- TASK 5 - OUTPUT 14

SELECT DISTINCT PR.PROJNO, PR.PROJNAME, EA.ACTNO
FROM PROJECT PR, EMP_ACT EA
WHERE PR.PROJNO = EA.PROJNO
AND PR.PROJNO LIKE 'AD%'
ORDER BY PR.PROJNO, EA.ACTNO;

-- TASK 6

SELECT DISTINCT E.EMPNO, E.LASTNAME, P.PROJNO
FROM EMPLOYEE E, PROJECT P, EMP_ACT EA
WHERE E.EMPNO = EA.EMPNO
AND P.PROJNO = EA.PROJNO
AND P.PROJNO = 'AD3113'
ORDER BY E.EMPNO, P.PROJNO;


-- TASK 7

SELECT E.EMPNO, P.PROJNO, P.PROJNAME, EA.ACTNO, EA.EMSTDATE
FROM EMPLOYEE E, PROJECT P, EMP_ACT EA
WHERE E.EMPNO = EA.EMPNO
AND P.PROJNO = EA.PROJNO
AND EA.EMSTDATE = '1982-10-1'
ORDER BY P.PROJNO, E.EMPNO, EA.ACTNO;

-- TASK 8

SELECT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EA.ACTNO
FROM EMPLOYEE E, EMP_ACT EA, PROJECT P
WHERE E.WORKDEPT = 'A00'
AND E.EMPNO = EA.EMPNO
AND P.PROJNO = EA.PROJNO
ORDER BY P.PROJNAME, EA.ACTNO;

-- TASK 9

SELECT DISTINCT E.WORKDEPT, E.LASTNAME, P.PROJNAME, EA.ACTNO 
FROM EMPLOYEE E, PROJECT P, EMP_ACT EA
WHERE E.EMPNO = EA.EMPNO
AND P.PROJNO = EA.PROJNO
AND E.WORKDEPT BETWEEN 'A00' AND 'C01'
ORDER BY E.WORKDEPT, E.LASTNAME, EA.ACTNO;

-- TASK 10

SELECT EA.ACTNO, D.MGRNO, EA.EMSTDATE, P.PROJNO, E.LASTNAME 
FROM EMPLOYEE E, EMP_ACT EA, DEPARTMENT D, PROJECT P
WHERE EA.EMSTDATE >= '1982-10-15'
AND E.EMPNO = EA.EMPNO
AND P.PROJNO = EA.PROJNO
AND D.DEPTNO = E.WORKDEPT
ORDER BY EA.ACTNO, EA.EMSTDATE;

-- TASK 11

SELECT D.DEPTNO, E_MAN.LASTNAME AS MANAGER, E_EMP.LASTNAME AS EMPLOYEE, E_MAN.HIREDATE, E_EMP.HIREDATE
FROM EMPLOYEE E_EMP, EMPLOYEE E_MAN, DEPARTMENT D
WHERE D.DEPTNO = 'A00'
AND E_EMP.WORKDEPT = D.DEPTNO
AND E_MAN.EMPNO = D.MGRNO
AND E_EMP.HIREDATE < E_MAN.HIREDATE
ORDER BY E_EMP.LASTNAME;